import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#3f465c",
        outline: "#76777d",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "inverse-surface": "#213145",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-container": "#684000",
        "on-secondary-fixed": "#2a1700",
        "inverse-on-surface": "#eaf1ff",
        primary: "#000000",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45464d",
        background: "#f8f9ff",
        secondary: "#855300",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#6ffbbe",
        surface: "#f8f9ff",
        "outline-variant": "#c6c6cd",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#ffb95f",
        "tertiary-container": "#002113",
        "on-tertiary-container": "#009668",
        "on-primary-container": "#7c839b",
        "surface-container-high": "#dce9ff",
        "secondary-container": "#fea619",
        "inverse-primary": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        tertiary: "#000000",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#eff4ff",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#565e74",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "on-surface": "#0b1c30",
        "surface-bright": "#f8f9ff",
        "primary-container": "#131b2e",
        "on-secondary-fixed-variant": "#653e00",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffddb8",
        "on-tertiary-fixed": "#002113",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        gutter: "16px",
      },
      maxWidth: {
        "max-width": "1440px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "mono-data": ["var(--font-jetbrains)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-md": [
          "14px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "mono-data": [
          "13px",
          { lineHeight: "1", letterSpacing: "0", fontWeight: "500" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
